services:
    app-db:
        image: postgres:16.0-alpine3.18
        container_name: ${PG_CONTAINER}
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_INITDB_ARGS: ${POSTGRES_INITDB_ARGS}
            TZ: ${TIME_ZONE}
        ports:
            - "5432:5432"
        volumes:
            - postgres:/var/lib/postgresql/data

    app:
        container_name: ${APP_CONTAINER}
        build: .
        ports:
            - "8080:8080"
        depends_on:
            - app-db
        environment:
            spring.datasource.main.jdbc-url: jdbc:postgresql://app-db:5432/${POSTGRES_DB}
            spring.datasource.main.username: ${POSTGRES_USER}
            spring.datasource.main.password: ${POSTGRES_PASSWORD}
            TZ: ${TIME_ZONE}
        volumes:
            - app-data:/app-service

volumes:
    postgres:
    app-data: