spring:
    jpa:
        properties:
            hibernate:
                generate_statistics: true
                jdbc:
                    batch_size: 20
        open-in-view: false

decorator:
    datasource:
        datasource-proxy:
            format-sql: true

logging:
    level:
        net.ttddyy.dsproxy.listener: DEBUG
        org.springframework.service: DEBUG
        org.springframework.security: TRACE
        org.springframework.aop: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
