school:
    max-courses-per-student: ${MAX_COURSES_PER_STUDENT:3}
spring:
    config:
        import: optional:file:./.env[.properties]
    datasource:
        main:
            driver-class-name: org.postgresql.Driver
            jdbc-url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
            username: ${POSTGRES_USER}
            password: ${POSTGRES_PASSWORD}
            hikari:
                minimum-idle: 1
                maximum-pool-size: 5
    jpa:
        properties:
            hibernate:
                generate_statistics: true
                jdbc:
                    batch_size: 20
        open-in-view: false
