logging:
    level:
        net.ttddyy.dsproxy.listener: debug
        springframework.service: DEBUG
        org.springframework.aop: DEBUG
        org.hibernate.SQL: debug
        org.hibernate.type.descriptor.sql.BasicBinder: trace


decorator:
    datasource:
        datasource-proxy:
            format-sql: true


school:
    max-courses-per-student: ${MAX_COURSES_PER_STUDENT:3}
spring:
    config:
        import: file:src/main/resources/.env[.properties]
    datasource:
        main:
            driver-class-name: org.postgresql.Driver
            jdbc-url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
            username: ${POSTGRES_USER}
            password: ${POSTGRES_PASSWORD}
            hikari:
                minimum-idle: 1
                maximum-pool-size: 5
    jpa:
        properties:
            hibernate:
                generate_statistics: true
                jdbc:
                    batch_size: 20
        open-in-view: false
