version: "3.8"
services:
    postgresql:
        image: postgres:16.0-alpine3.18
        container_name: ${PG_CONTAINER}
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_INITDB_ARGS: ${POSTGRES_INITDB_ARGS}
            TZ: ${TIME_ZONE}
        ports:
            - ${POSTGRES_PORT}:5432
        networks:
            - postgres
        volumes:
            - postgres:/data/postgres

networks:
    postgres:
        driver: bridge

volumes:
    postgres: